name: Init

on: [create, workflow_dispatch]

permissions: 
  issues: write
  contents: read

jobs:
  initialize_repo:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Create Issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create -t "❓ What is your experience with GitHub?" -b "What is your experience with GitHub? Whats is your experience with other CI/CD tools? Comment below 👇"
          gh issue create -t "❓ What do you want to learn?" -b "What is it you want to learn? What specific scenarios are you interested in? Comment below 👇"

          gh issue create -t "🔍 Morning Retro: What was good?" -b "What did you like in this first half of this course? What was good? Comment below 👇"
          gh issue create -t "❤️ What was the best feature you learned?" -b "What was the GitHub Actions feature you liked best that you have learned about the first time? If you want add your hobby to share it with the group. Comment below 👇"        
          gh issue create -t "🔍 Afternoon Retro: What was good?" -b "What did you like in the second half of this course? What was good? Comment below 👇"
          gh issue create -t "🔍 Afternoon Retro: What can be improved?" -b "What can be improved? What was missing? Any additional comments? Comment below 👇"
